services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/src

  app:
    container_name: "php"
    build:
      context: ./docker/php
    volumes:
      - ./:/src
      - node_modules:/src/node_modules
      - vendor:/src/vendor
      - ./docker/php/etc/:/usr/local/etc/php/

  db:
    image: mysql:latest
    container_name: "mysql"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  cache:
    image: redis:latest
    container_name: "cache"

volumes:
  vendor:
  node_modules:
  db-data:
